version: '3.4'

services:
  flask_app:
    image: covid_viz_flask:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./static:/static
    - ./sample_json:/sample_json
    ports:
      - 5000:5000